### ISSUE TITLE
Instance manager closing automatically

### ISSUE THREAD

**Issue by ionizedparticle** [Sightem/Instance-Manager#1]
i open it as administrator, i can only see 2 messages in the console before they close but its covered up by the main ui so i cant tell you what they're saying

missing dependencies? idk

**Comment by Sightem** [comment]
Which version are you trying to use?

**Comment by ionizedparticle** [comment]
> Which version are you trying to use?

It matters not, all of them close

**Comment by Sightem** [comment]
Can you join the discord so we can diagnose the issue easier? [https://discord.gg/fqwDK7xc](https://discord.gg/fqwDK7xc)
